<?php
/**
 * @file
 * feature_articles.features.field_base.inc
 */

/**
 * Implements hook_field_default_field_bases().
 */
function feature_articles_field_default_field_bases() {
  $field_bases = array();

  // Exported field_base: 'field_primary_image'.
  $field_bases['field_primary_image'] = array(
    'active' => 1,
    'cardinality' => 1,
    'deleted' => 0,
    'entity_types' => array(),
    'field_name' => 'field_primary_image',
    'indexes' => array(
      'fid' => array(
        0 => 'fid',
      ),
    ),
    'locked' => 0,
    'module' => 'mediafield',
    'settings' => array(),
    'translatable' => 0,
    'type' => 'media',
  );

  return $field_bases;
}
